
server:
  port: 9001

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.16.33.131:3306/users
    username: users
    password: 1234
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql:true
        format_sql:true
   